### ISSUE TITLE
Refactor EventoController into 2 files

### ISSUE THREAD

**Issue by Antoniobox** [Lorenzom54/CRUDJava#2]
### **Propuesta**

**EventoController contiene** tanto **acciones** que derivan de acciones dedicadas al **CRUD** como **acciones** dedicadas por ejemplo a las acciones de la **ventana**.

Sería más correcto **dividir** esa **funcionalidad en distintos controladores** para una **organización más limpia y más correcta**.

**Comment by Lorenzom54** [comment]
Buenas Antonio, muchas gracias por realizar la peticion, veo que tiene sentido lo que dices. Dividiré el controlador en varios.

Muchas Gracias por tu comentario.😉
